name: caller

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-reusable:
    name: call reusable
    uses: vrossiciandt/reusable/.github/workflows/reusable.yaml@main
    secrets: inherit