name: Artifact Demo
on:
  workflow_dispatch:
jobs:
  job-a:
    name: Job A - Generate Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Create test files
        run: |
          mkdir -p artifact-data
          echo "This is file 1 from Job A" > artifact-data/file1.txt
          echo "This is file 2 from Job A" > artifact-data/file2.txt
          echo "Job A execution time: $(date)" > artifact-data/job-a-info.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: job-a-artifact
          path: artifact-data
          retention-days: 1
          overwrite: true
          if-no-files-found: ignore

  job-b:
    name: Job B - Process Artifact
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from Job A
        uses: actions/download-artifact@v4
        with:
          name: job-a-artifact
          path: artifact-data
      
      - name: List downloaded files
        run: |
          echo "Files downloaded in Job B:"
          ls -la artifact-data/
      
      - name: Add Job B content
        run: |
          echo "This is a file added by Job B" > artifact-data/job-b-file.txt
          echo "Job B processed this artifact at: $(date)" >> artifact-data/job-b-info.txt
          
      - name: Upload modified artifact
        uses: actions/upload-artifact@v4
        with:
          name: job-a-artifact
          path: artifact-data
          retention-days: 1
          overwrite: true
          if-no-files-found: ignore

  job-c:
    name: Job C - Process Artifact
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from Job A
        uses: actions/download-artifact@v4
        with:
          name: job-a-artifact
          path: artifact-data
      
      - name: List downloaded files
        run: |
          echo "Files downloaded in Job C:"
          ls -la artifact-data/
      
      - name: Add Job C content
        run: |
          echo "This is a file added by Job C" > artifact-data/job-c-file.txt
          echo "Job C processed this artifact at: $(date)" >> artifact-data/job-c-info.txt

      - name: Wait 2 and Last Try
        run: |
          sleep 2
        shell: bash
          
      - name: Upload modified artifact
        uses: actions/upload-artifact@v4
        with:
          name: job-a-artifact
          path: artifact-data
          retention-days: 1
          overwrite: true
          if-no-files-found: ignore

  job-d:
    name: Job D - Final Processing
    needs: [job-b, job-c]
    runs-on: ubuntu-latest
    steps:
      - name: Download final artifact
        uses: actions/download-artifact@v4
        with:
          name: job-a-artifact
          path: final-data
      
      - name: Analyze final artifact content
        run: |
          echo "Final artifact contents:"
          ls -la final-data/
          
          echo ""
          echo "Contents of files:"
          cat final-data/*.txt
          
          echo ""
          echo "Checking for expected files..."
          
          # Verificar arquivos do Job A
          if [ -f "final-data/file1.txt" ] && [ -f "final-data/file2.txt" ]; then
            echo "✅ Job A files present"
          else
            echo "❌ Job A files missing"
          fi
          
          # Verificar arquivo do Job B
          if [ -f "final-data/job-b-file.txt" ]; then
            echo "✅ Job B file present"
          else
            echo "❌ Job B file missing"
          fi
          
          # Verificar arquivo do Job C
          if [ -f "final-data/job-c-file.txt" ]; then
            echo "✅ Job C file present"
          else
            echo "❌ Job C file missing"
          fi
