name: caller  

on:
  workflow_dispatch:
    inputs:
      ultrasecrevalue:
        description: 'Segredo não tão segredo assm'
        required: true

jobs:
  generate-secret:
    runs-on: ubuntu-latest
    steps:
    - name: generate-secret
      shell: bash
      run: |
        the_secret=${{ inputs.ultrasecretvalue }}
        echo "::add-mask::$the_secret"
        echo "secret=$the_secret" >> "$GITHUB_OUTPUT"
    - name: validate-secret
      env:
        SECRET: ${{ steps.generate-secret.outputs.secret }}
      shell: bash
      run: |
        echo "test"