name: caller  

on:
  workflow_dispatch:
    inputs:
      ultrasecretvalue:
        description: 'Segredo não tão segredo assim'
        required: true

jobs:
  generate-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask
        id: add_mask
        run: |
          INP_SECRET=$(jq -r '.inputs.ultrasecretvalue' $GITHUB_EVENT_PATH)

          echo ::add-mask::$INP_SECRET


          echo ULTRASECRETVALUE="$INP_SECRET" >> $GITHUB_ENV
      - name: Check output from another step
        run: |
          echo "${{ steps.add_mask.outputs.ultrasecretvalue }}"

      - name: Check environment variables 1
        run: |
          echo "${{ env.ULTRASECRETVALUE }}"

      - name: Check environment variables 2
        env:
          TE: ${{ env.ULTRASECRETVALUE }}
        run: |
          echo $ULTRASECRETVALUE