name: caller  

on:
  workflow_dispatch:
    inputs:
      ultrasecretvalue:
        description: 'Segredo não tão segredo assim'
        required: true

jobs:
  generate-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Mask
      run: |
        echo "::add-mask::${{ inputs.ultrasecretvalue }}"
    - name: validate-secret
      env:
        SECRET: ${{ inputs.ultrasecretvalue }}
      shell: bash
      run: |
        echo "$SECRET"