name: caller  

on:
  workflow_dispatch:
    inputs:
      ultrasecretvalue:
        description: 'Segredo não tão segredo assim'
        required: true

jobs:
  generate-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask
        id: add_mask
        run: |
          ultrasecretvalue=$(jq -r '.inputs.ultrasecretvalue' $GITHUB_EVENT_PATH)

          echo ::add-mask::$ultrasecretvalue
      - name: Check output from another step
        run: |
          echo "${{ github.event.inputs.ultrasecretvalue }}"

      - name: Check environment variables 1
        run: |
          echo "${{ inputs.ultrasecretvalue }}"